### PR TITLE
Integrate images for roulette units

### PR DESCRIPTION
**Pull request by antoninhrlt**
Roulette can now handle images in the sections.

`RouletteGroup.uniformImages` is added.
See how it is drawn [here](https://github.com/antoninhrlt/roulette/blob/main/lib/src/roulette_paint.dart#L102).

## Media
Roulette preview with images

## Important note
To make that change possible, we had to make `group` from `RouletteController` nullable and not required at controller's construction.
```dart
  factory RouletteController({
    RouletteGroup? group,
    required TickerProvider vsync,
  })
```
See the [example](https://github.com/antoninhrlt/roulette/blob/main/example/lib/main.dart).

### CODE REVIEW

**Comment by do9core** [comment]
Apologies for the late reply. 

The `RoulettePainter` class is becoming overly complex as we add support for rendering more content types. 
To improve maintainability, we could refactor it by extracting separate painter delegate for each content type we need to draw. Let me know if you'd like me to take a first pass at splitting up the painter, or if you have any other suggestions on how to best refactor it.

Also, I noticed you seem to have uploaded some runtime files in the example folder - please avoid uploading those files :)

**Comment by antoninhrlt** [comment]
> Apologies for the late reply.
> 
> The `RoulettePainter` class is becoming overly complex as we add support for rendering more content types. To improve maintainability, we could refactor it by extracting separate painter delegate for each content type we need to draw. Let me know if you'd like me to take a first pass at splitting up the painter, or if you have any other suggestions on how to best refactor it.

Ok. I guess I can commit new changes that separate these for a better organisation in the project. You will see them soon.

> Also, I noticed you seem to have uploaded some runtime files in the example folder - please avoid uploading those files :)

Sorry, they will be removed in the next commit.

**Comment by antoninhrlt** [comment]
Here we are

**Comment by do9core** [comment]
I tried out the example code and found it a bit difficult to use on the user side. 

To make `RouletteUnit` more intuitive like the `Image` widget in Flutter, I'm working with the `ImageProvider` to improve it.

**Comment by antoninhrlt** [comment]
Yes you're right. That's the problem to have ui.Image and Image and have to get async to translate one to another

**Comment by do9core** [comment]
Implemented. And added the image roulette presentation test.

- [x] May also need to finish the error handling logic.
- [x] Maybe the `RouletteGroup` in `RouletteController` is no need to be nullable now.

**Comment by do9core** [comment]
Finished.

**Comment by antoninhrlt** [comment]
Well done ! Can't wait to test it

**Comment by do9core** [comment]
Seems the Github Actions task using the stable version of flutter which is not compatible with current project flutter version so the presentation test cannot pass, I'll update the action script or flutter version.

If you want to use it now, you can try the git ref way in pubspec.yaml

**Comment by antoninhrlt** [comment]
Please, don't update the Flutter version otherwise the apps using it might not work anymore.
I think it would be better to just update the action script.

I'll wait for your changes, no problem.

Thank you

**Comment by do9core** [comment]
Github Actions updated. I'm merging this branch into main.

I would publish a new version after update the README.md and example.

Thanks for the contribution again :)

**Comment by antoninhrlt** [comment]
Cool ! Thank you

**Pull request merged**
